############# German navigation ##############

[[main]]
name = "Leistungen"
url = "/leistungen"
weight = 1

[[main]]
name = "Projekte"
url = "/projekte"
weight = 2

[[main]]
name = "Team"
url = "/team"
weight = 3

[[main]]
name = "Kontakt"
url = "/kontakt"
weight = 4

[[footer]]
name = "Datenschutz"
url = "/datenschutz"
weight = 3

[[footer]]
name = "Impressum"
url = "/impressum"
weight = 4
